# Generated by cucumber-sinatra. (2014-09-30 09:48:35 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/sinatra_app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = SinatraApp

class SinatraAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SinatraAppWorld.new
end
